### PR TITLE
Skip next and previous links in folder view

### PR DESCRIPTION
**Pull request by JohnnyLAmpAz**
To prevent unwanted crawling from folder view, which I discussed in #17 , I came up with this simple fix that works in my situation. That is to just skip those URLs if the `id` matches `prev-activity-link` or `next-activity-link`.

I don't think that this may cause problems with other institutions' Moodle layout, because if there is no link identified as such nothing changes. Furthermore I think this might be found in some older versions of Moodle, because if it was something custom made from my university I would expect to find some `id` values in Italian language :laughing: .

Here my situation:

screen2

### CODE REVIEW

**Comment by rssws** [comment]
Hi @JohnnyLAmpAz ,

thanks a lot for your interest in contributing to the repo.

I reviewed your changes. It could work for your case. However, I have checked both the moodle from my university and the official moodle demo. Both of them do not have the prev and next links.

In general, I would avoid using any HTML id or class to decide whether to crawl. But what you've mentioned is indeed an unwanted behavior. The root reason why we don't want to crawl the prev and next links is a folder in moodle cannot contain any other resource page or folder (except for the subfolder, which is not a real folder anyway).

So I would suggest fixing this issue by only adding `modResourceView` and `pluginfile` to the crawling queue if the current resource is `modFolderView`. Or simply skip the current URL from a `modFolderView` if the target resource is of type `courseResources` or `modFolderView` or `courseView`. :)

**Comment by JohnnyLAmpAz** [comment]
> So I would suggest fixing this issue by only adding modResourceView and pluginfile to the crawling queue if the current resource is modFolderView.

This is what I started with because of HTML attributes non-dependency, which is grate. But then encountered the situation in the screenshot above where one of the links (the _previous_ one) was actually a file and not another folder, which is of type `modResourceView`: indistinguishable from the actual folder's files. So it kinda felt like an half fix to me and came up with the proposed solution.

In the end I think one can indeed just use that button to download the folder. If you're ok with it in these days I'm gonna re-implement the solution you also suggested just to exclude that folder-to-folder link, which apparently in standard Moodle versions wont appear but in others like mine does.

**Comment by rssws** [comment]
> > So I would suggest fixing this issue by only adding modResourceView and pluginfile to the crawling queue if the current resource is modFolderView.
> 
> This is what I started with because of HTML attributes non-dependency, which is grate. But then encountered the situation in the screenshot above where one of the links (the _previous_ one) was actually a file and not another folder, which is of type `modResourceView`: indistinguishable from the actual folder's files. So it kinda felt like an half fix to me and came up with the proposed solution.
> 
> In the end I think one can indeed just use that button to download the folder. If you're ok with it in these days I'm gonna re-implement the solution you also suggested just to exclude that folder-to-folder link, which apparently in standard Moodle versions wont appear but in others like mine does.

Instead of crawling `id=page` or even the entire page, how about we crawl the `<div role="main">...<div>`. I believe this element contains all URLs that we need and excludes your prev and next navigators as well.

You can check [this line](https://github.com/rssws/moodle-dl-ext/blob/50c928b758d057e2d73d752f43099cd106ada00f/packages/content-script/src/moodle-files.ts#L124) and add `main` before `page` just in case this element doesn't exist somehow.

**Comment by JohnnyLAmpAz** [comment]
Noticed that div before but I did't think about the possibility to query based on that `role` attribute. Works well!

**Comment by rssws** [comment]
Nicely done with `querySelector`! After you fix the code style issue, I think we can merge it. :) Try to run `yarn lint:fix` to fix automatically.

**Comment by JohnnyLAmpAz** [comment]
Whoops. Done manually. I did not have installed ESLint

**Comment by JohnnyLAmpAz** [comment]
again... With `yarn package` haven't got any error, so couldn't figure out. Is there a way to make yarn do the same check as official build does?

**Comment by rssws** [comment]
> again... With `yarn package` haven't got any error, so couldn't figure out. Is there a way to make yarn do the same check as official build does?

I believe you can run `yarn lint:fix` in the root folder of the project since `eslint` is a dev dependency. `yarn package` does only building and packaging.

Otherwise, LGTM.

**Review by rssws — APPROVED** [review]

**Pull request merged**
